config/routes.rb
Rails.application.routes.draw do

  #root
  root 'users#index'

  # Users
  match '/signup', :to => 'users#create', :via => [:post], :as => :create_user
  match '/update', :to => 'users#update', :via => [:patch], :as => :update_user
  get '/signup' => 'users#new', as: :signup
  get '/me' => 'users#show', as: :show_user
  get '/update' => 'users#edit', as: :edit_user
  get '/validate_user', :to => "users#validate_user"

  # Sessions
  match '/login', :to => 'sessions#create', :via => [:post], :as => :login_user
  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  # Password Reset
  get '/forgot-password' => 'password_reset#new', as: :forgot_password
  match '/forgot-password', :to => 'password_reset#verify_username', :via => [:post], :as => :verify_username
  get '/forgot-password/1' => 'password_reset#new'
  match '/forgot-password/1', :to => 'password_reset#verify_security_answer', :via => [:post], :as => :verify_security_answer
  get '/forgot-password/reset-password' => 'password_reset#new'
  match '/forgot-password/reset-password', :to => 'password_reset#reset_password', :via => [:patch], :as => :reset_password

  # Albums and assets
  resources :albums do
    resources :assets
    resources :filters do
      resources :tags
    end
  end

  #Filters and tags
  get '/albums/:album_id/distill' => 'filters#show', as: :distill_album
  get '/albums/:album_id/distilled_albums' => 'filters#distilled_albums', as: :distilled_album
  get '/albums/:album_id/distilled_albums/:tag_id' => 'filters#assets_with_tag', as: :distilled_assets
  get '/albums/:album_id/distilled_albums/:tag_id/download' => 'albums#download', as: :download_album

  match '/albums/:album_id/filters/add_filter_to_album', :to => 'filters#add_filter_to_album', :via => [:post], :as => :add_filter_to_album
  match '/albums/:album_id/filters/remove_filter_from_album', :to => 'filters#remove_filter_from_album', :via => [:post], :as => :remove_filter_from_album
  match '/tags/assign_tag_to_asset', :to => 'tags#assign_tag_to_asset', :via => [:post], :as => :assign_tag_to_asset

  get '/albums/:album_id/asset/:asset_id/tags' => "assets#tags", as: :asset_tags
  get '/assets/asset_belongs_to_current_user' => "assets#asset_belongs_to_current_user", as: :asset_belongs_to_current_user


  #Shared Albums
  #resources :shared_albums
  match '/shared_albums/share_album', :to => 'shared_albums#share_album', :via => [:post], :as => :share_album
  get '/shared_album/:shared_album_id' => 'shared_albums#show', as: :shared_album
  match '/shared_albums/delete_album', :to => 'shared_albums#destroy', :via => [:post], :as => :delete_share_album

end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new
  end

  def verify_username
    @user = User.find_by_username(params[:username])
    if @user
      render 'prompt_security_question'
    else
      flash.now[:danger] = "Uh oh! Looks like there is no account with the username you entered."
      render 'new'
    end
  end

  def verify_security_answer
    @user = User.find_by_username(params[:username])
    if !@user
      redirect_to :forgot_password
      return
    end

    if @user.security_answer == params[:security_answer]
      render 'password_reset'
    else
      flash.now[:danger] = "Uh oh! The answer is incorrect."
      render 'prompt_security_question'
    end
  end

  def reset_password
    @user = User.find_by_username(params[:username])
    if @user.update(edit_user_params)
      redirect_to root_url, :flash => { :success => "Password has been successfully reset!" }
    else
      flash.now[:info] = "Update Unsuccessful!"
      render 'password_reset'
    end
  end


  private
    def edit_user_params
      params[:user].permit(:password, :password_confirmation)
    end

end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/new.html.erb
<div class="row col-md-6 col-xs-10 col-md-offset-3 col-xs-offset-1">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Forget Password (Step 1/3)</h3>
    </div>
    <div class="panel-body">
      <%= form_tag verify_username_path , { :class => 'form-horizontal' , :role => 'form' } do %>
      <div class="form-group">
        <%= label_tag :username , raw(icon("account_circle")), :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= text_field_tag :username , params[:username] , :class => 'form-control', :required => true, :placeholder => 'Username' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= button_tag(type: 'submit', class: "btn btn-success") do %>
          Next
          <i class="material-icons right v-bottom">send</i>
          <% end %>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/password_reset/password_reset.html.erb
<div class="row col-lg-8 col-md-6 col-xs-10 col-lg-offset-2 col-md-offset-3 col-xs-offset-1">
	<% if @user.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
 			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
 			 <strong>Oops!</strong>
 			  <% for message in @user.errors.full_messages %>
		  		<li><%= message %></li>
			  <% end %>
		</div>
	<% end %>
	<div class="panel panel-success">
  		<div class="panel-heading">
    		<h3 class="panel-title">Password Reset (Step 3/3)</h3>
  		</div>

	  	<div class="panel-body">
			<%= form_for @user , :url => reset_password_path , :html => { :class => 'form-horizontal' } do |f| %>
			    <div class="form-group">
			        <%= f.label :password , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
                  <%= hidden_field_tag("username", @user.username) %>
			            <%= f.password_field :password , :class => 'form-control', :required => true, :pattern => "(?=^.{6,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$", :title => "It should be more than 6 characters and should contain 3 of the options (Uppercase characters, Lowercase characters, Numbers, or Special characters)" %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label :password_confirmation , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password_confirmation , :class => 'form-control', :required => true %>
			        </div>
			    </div>
			    <div class="form-group">
			        <div class="col-sm-offset-3 col-sm-9">
			            <%= submit_tag "Update" , :class => 'btn btn-success' %>
			        </div>
			    </div>
			<% end %>
		</div>
  	</div>
</div>

app/views/password_reset/prompt_security_question.html.erb
<div class="row col-md-6 col-xs-10 col-md-offset-3 col-xs-offset-1">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Forget Password (Step 2/3)</h3>
    </div>
    <div class="panel-body">
      <%= form_tag verify_security_answer_path , { :class => 'form-horizontal' , :role => 'form' } do %>
      <div class="form-group">
        <div class="col-sm-12">

          <p><%= @user.security_question %></p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <%= hidden_field_tag("username", @user.username) %>
          <%= text_field_tag :security_answer , params[:security_answer] , :class => 'form-control', :required => true, :placeholder => 'Answer' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <%= button_tag(type: 'submit', class: "btn btn-success") do %>
          Next
          <i class="material-icons right v-bottom">send</i>
          <% end %>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>