config/routes.rb
Rails.application.routes.draw do

  #root
  root 'users#index'

  # Users
  match '/signup', :to => 'users#create', :via => [:post], :as => :create_user
  match '/update', :to => 'users#update', :via => [:patch], :as => :update_user
  get '/signup' => 'users#new', as: :signup
  get '/me' => 'users#show', as: :show_user
  get '/update' => 'users#edit', as: :edit_user
  get '/validate_user', :to => "users#validate_user"

  # Sessions
  match '/login', :to => 'sessions#create', :via => [:post], :as => :login_user
  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  # Password Reset
  get '/forgot-password' => 'password_reset#new', as: :forgot_password
  match '/forgot-password', :to => 'password_reset#verify_username', :via => [:post], :as => :verify_username
  get '/forgot-password/1' => 'password_reset#new'
  match '/forgot-password/1', :to => 'password_reset#verify_security_answer', :via => [:post], :as => :verify_security_answer
  get '/forgot-password/reset-password' => 'password_reset#new'
  match '/forgot-password/reset-password', :to => 'password_reset#reset_password', :via => [:patch], :as => :reset_password

  # Albums and assets
  resources :albums do
    resources :assets
    resources :filters do
      resources :tags
    end
  end

  #Filters and tags
  get '/albums/:album_id/distill' => 'filters#show', as: :distill_album
  get '/albums/:album_id/distilled_albums' => 'filters#distilled_albums', as: :distilled_album
  get '/albums/:album_id/distilled_albums/:tag_id' => 'filters#assets_with_tag', as: :distilled_assets
  get '/albums/:album_id/distilled_albums/:tag_id/download' => 'albums#download', as: :download_album

  match '/albums/:album_id/filters/add_filter_to_album', :to => 'filters#add_filter_to_album', :via => [:post], :as => :add_filter_to_album
  match '/albums/:album_id/filters/remove_filter_from_album', :to => 'filters#remove_filter_from_album', :via => [:post], :as => :remove_filter_from_album
  match '/tags/assign_tag_to_asset', :to => 'tags#assign_tag_to_asset', :via => [:post], :as => :assign_tag_to_asset

  get '/albums/:album_id/asset/:asset_id/tags' => "assets#tags", as: :asset_tags
  get '/assets/asset_belongs_to_current_user' => "assets#asset_belongs_to_current_user", as: :asset_belongs_to_current_user


  #Shared Albums
  #resources :shared_albums
  match '/shared_albums/share_album', :to => 'shared_albums#share_album', :via => [:post], :as => :share_album
  get '/shared_album/:shared_album_id' => 'shared_albums#show', as: :shared_album
  match '/shared_albums/delete_album', :to => 'shared_albums#destroy', :via => [:post], :as => :delete_share_album

end

app/models/user.rb
require "open-uri"

class User < ActiveRecord::Base
  attr_accessor :password, :fullname
  before_save :encrypt_password, :update_user_avatar

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :first_name, :last_name, :username, :email, :security_question, :security_answer
  validates_uniqueness_of :email, :username

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ""
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :albums, dependent: :destroy
  has_many :filters, dependent: :destroy
  has_many :sharedAlbums, dependent: :destroy

  def self.authenticate (username,password)
    user = find_by_username(username)
    if user && password_matches?(user,password)
      user
    end
  end

  def fullname
    "#{first_name} #{last_name}"
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def update_user_avatar
    unless avatar?
      uri = URI.encode("http://avatarly.herokuapp.com/avatar?size=300&text=#{fullname}")
      self.avatar = URI.parse(uri)
      self.avatar_file_name = "avatar.jpeg"
    end
  end

  private
  def self.password_matches?(user,password_supplied)
     user.password_hash == BCrypt::Engine.hash_secret(password_supplied, user.password_salt)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, :only => [:edit, :update]
  def index
    if current_user
      @albums = current_user.albums.all
      @album = current_user.albums.new
      @shared_albums = shared_albums_with_current_user
      render :show
    else
      redirect_to login_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :flash => { :success => "Congratulations! You have successfully signed up." }
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(edit_user_params)
      flash.now[:success] = "Updated Successfully!"
    else
      flash.now[:info] = "Update Unsuccessful!"
    end
    render 'edit'
  end

  def validate_user
    user = User.find_by_username(params[:username])
    if user
      render json: { message: "success" }, :status => 200
    else
      render json: { error: 'Sorry, no user found'}, :status => 400
    end
  end

  private
  def user_params
   params[:user].permit(:first_name, :last_name, :username, :password, :password_confirmation, :email, :security_question, :security_answer)
  end

  def edit_user_params
    params[:user].permit(:avatar, :first_name, :last_name, :password, :password_confirmation, :email, :security_question, :security_answer)
  end

  def require_login
    if !current_user
      redirect_to root_url
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def security_questions
    ['What\'s your nickname?','What\'s your favourite sport?', 'What\'s your mothers maiden name?','What\'s the name of your first school?','What\'s your favourite hobby?']
  end
  
end

app/views/users/edit.html.erb
<div class="row col-lg-8 col-md-6 col-xs-10 col-lg-offset-2 col-md-offset-3 col-xs-offset-1">
	<% if @user.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
 			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
 			 <strong>Oops!</strong>
 			  <% for message in @user.errors.full_messages %>
		  		<li><%= message %></li>
			  <% end %>
		</div>
	<% end %>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h3 class="panel-title">Edit</h3>
  		</div>

	  	<div class="panel-body">
			<%= form_for @user , :url => update_user_path, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>

				<div class="form-group">
					<div class="col-sm-12 text-center ">
						<div class="user-avatar-container">
							<%=	image_tag(current_user.avatar.url(:medium),  class: "img-circle", width: "100", id: "user-avatar") %>
							<button type="button" class="btn btn-default btn-sm" id="user-avatar-edit-button">
	  						<i class="material-icons prefix">photo_camera</i>
							</button>
							<%= f.file_field :avatar %>
						</div>
				 </div>
				</div>

				<div class="form-group">
						<%= f.label :first_name , :class => 'col-sm-3 control-label' %>
						<div class="col-sm-9">
								<%= f.text_field :first_name , :class => 'form-control', :required => true,  :pattern => ".{1,25}", :title => "1 to 25 characters" %>
						</div>
				</div>

				<div class="form-group">
						<%= f.label :last_name , :class => 'col-sm-3 control-label' %>
						<div class="col-sm-9">
								<%= f.text_field :last_name , :class => 'form-control', :required => true,  :pattern => ".{1,25}", :title => "1 to 25 characters" %>
						</div>
				</div>

				<div class="form-group">
						<%= f.label :password , :class => 'col-sm-3 control-label' %>
						<div class="col-sm-9">
								<%= f.password_field :password , :class => 'form-control', :pattern => "(?=^.{6,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$", :title => "It should be more than 6 characters and should contain 3 of the options (Uppercase characters, Lowercase characters, Numbers, or Special characters)" %>
						</div>
				</div>

			    <div class="form-group">
			        <%= f.label :password_confirmation , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password_confirmation , :class => 'form-control' %>
			        </div>
			    </div>

					<div class="form-group">
			        <%= f.label :email , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :email , :class => 'form-control', :required => true, :type => "email" %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label :security_question , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			       		<%= f.select(:security_question, options_for_select(security_questions, @user.security_question), {}, {:class => 'form-control', :required => true}) %>
			        </div>
			    </div>

          <div class="form-group">
              <%= f.label :security_answer , :class => 'col-sm-3 control-label' %>
              <div class="col-sm-9">
                  <%= f.text_field :security_answer , :class => 'form-control', :required => true %>
              </div>
          </div>

			    <div class="form-group">
			        <div class="col-sm-offset-3 col-sm-9">
			            <%= submit_tag "Update" , :class => 'btn btn-primary' %>

			            <%= link_to 'Cancel', root_url, :class => 'btn btn-default' %>
			        </div>
			    </div>
			<% end %>
		</div>
  	</div>
</div>

app/views/users/new.html.erb
<div class="row col-lg-8 col-md-6 col-xs-10 col-lg-offset-2 col-md-offset-3 col-xs-offset-1">
	<% if @user.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
 			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
 			 <strong>Oops!</strong>
 			  <% for message in @user.errors.full_messages %>
		  		<li><%= message %></li>
			  <% end %>
		</div>
	<% end %>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h3 class="panel-title">Sign up!</h3>
  		</div>

	  	<div class="panel-body">
			<%= form_for @user , :url => create_user_path, :html => { :class => 'form-horizontal' } do |f| %>
			    <div class="form-group">
			        <%= f.label :first_name , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :first_name , :class => 'form-control', :required => true,  :pattern => ".{1,25}", :title => "1 to 25 characters" %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label :last_name , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :last_name , :class => 'form-control', :required => true,  :pattern => ".{1,25}", :title => "1 to 25 characters" %>
			        </div>
			    </div>

          <div class="form-group">
              <%= f.label :username , :class => 'col-sm-3 control-label' %>
              <div class="col-sm-9">
                  <%= f.text_field :username , :class => 'form-control', :required => true,  :pattern => "[^ ]{7,12}", :title => "7 to 12 characters with no spaces" %>
              </div>
          </div>

			    <div class="form-group">
			        <%= f.label :password , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password , :class => 'form-control', :required => true,  :pattern => "(?=^.{6,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$", :title => "It should be more than 6 characters and should contain 3 of the options (Uppercase characters, Lowercase characters, Numbers, or Special characters)" %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label :password_confirmation , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password_confirmation , :class => 'form-control', :required => true %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label :email , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :email , :class => 'form-control', :required => true, :type => "email" %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label :security_question , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			       		<%= f.select(:security_question, options_for_select(security_questions, @user.security_question), {} , {:class => 'form-control', :required => true}) %>
			        </div>
			    </div>

          <div class="form-group">
              <%= f.label :security_answer , :class => 'col-sm-3 control-label' %>
              <div class="col-sm-9">
                  <%= f.text_field :security_answer , :class => 'form-control', :required => true %>
              </div>
          </div>

			    <div class="form-group">
			        <div class="col-sm-offset-3 col-sm-9">
			            <%= submit_tag "Register" , :class => 'btn btn-primary' %>

			            <%= link_to 'Cancel', root_url, :class => 'btn btn-default' %>
			        </div>
			    </div>
			<% end %>
		</div>
  	</div>
</div>

app/views/users/show.html.erb
<div class="col-xs-12">
  <div class="row ">
    <%= render partial: "albums/new", object: @album %>
    <%= render @albums %>
  </div>
  <hr/>
  <%= render partial: "shared_albums/index" %>
</div>