config/routes.rb
Rails.application.routes.draw do

  #root
  root 'users#index'

  # Users
  match '/signup', :to => 'users#create', :via => [:post], :as => :create_user
  match '/update', :to => 'users#update', :via => [:patch], :as => :update_user
  get '/signup' => 'users#new', as: :signup
  get '/me' => 'users#show', as: :show_user
  get '/update' => 'users#edit', as: :edit_user
  get '/validate_user', :to => "users#validate_user"

  # Sessions
  match '/login', :to => 'sessions#create', :via => [:post], :as => :login_user
  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  # Password Reset
  get '/forgot-password' => 'password_reset#new', as: :forgot_password
  match '/forgot-password', :to => 'password_reset#verify_username', :via => [:post], :as => :verify_username
  get '/forgot-password/1' => 'password_reset#new'
  match '/forgot-password/1', :to => 'password_reset#verify_security_answer', :via => [:post], :as => :verify_security_answer
  get '/forgot-password/reset-password' => 'password_reset#new'
  match '/forgot-password/reset-password', :to => 'password_reset#reset_password', :via => [:patch], :as => :reset_password

  # Albums and assets
  resources :albums do
    resources :assets
    resources :filters do
      resources :tags
    end
  end

  #Filters and tags
  get '/albums/:album_id/distill' => 'filters#show', as: :distill_album
  get '/albums/:album_id/distilled_albums' => 'filters#distilled_albums', as: :distilled_album
  get '/albums/:album_id/distilled_albums/:tag_id' => 'filters#assets_with_tag', as: :distilled_assets
  get '/albums/:album_id/distilled_albums/:tag_id/download' => 'albums#download', as: :download_album

  match '/albums/:album_id/filters/add_filter_to_album', :to => 'filters#add_filter_to_album', :via => [:post], :as => :add_filter_to_album
  match '/albums/:album_id/filters/remove_filter_from_album', :to => 'filters#remove_filter_from_album', :via => [:post], :as => :remove_filter_from_album
  match '/tags/assign_tag_to_asset', :to => 'tags#assign_tag_to_asset', :via => [:post], :as => :assign_tag_to_asset

  get '/albums/:album_id/asset/:asset_id/tags' => "assets#tags", as: :asset_tags
  get '/assets/asset_belongs_to_current_user' => "assets#asset_belongs_to_current_user", as: :asset_belongs_to_current_user


  #Shared Albums
  #resources :shared_albums
  match '/shared_albums/share_album', :to => 'shared_albums#share_album', :via => [:post], :as => :share_album
  get '/shared_album/:shared_album_id' => 'shared_albums#show', as: :shared_album
  match '/shared_albums/delete_album', :to => 'shared_albums#destroy', :via => [:post], :as => :delete_share_album

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :assets, dependent: :destroy
  has_and_belongs_to_many :filters
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login

  def new
  end

  def create
    @album = current_user.albums.create(album_params)
    redirect_to @album
  end

  def show
    @album = current_user.albums.find_by_id( params[:id])
    @assets = @album.assets
    @asset = current_album.assets.new
  end

  def edit
    @album = current_user.albums.find_by_id( params[:id])
  end

  def update
    @album = current_user.albums.find_by_id( params[:id])
    @album.update(album_params)
    respond_to do |format|
      format.json { render json: @album }
    end
  end

  def destroy
    @album = current_user.albums.find_by_id(params[:id])
    @album.destroy
    redirect_to root_url
  end

  def download
    album = current_user.albums.find_by_id(params[:album_id])
    tag = Tag.find(params[:tag_id]) unless params[:tag_id] == "all"

    if(tag && album)
      assets = album.assets.with_tag(tag)
    else
      assets = album.assets
    end

    t = Tempfile.new('tmp-zip-' + request.remote_ip)
    Zip::ZipOutputStream.open(t.path) do |zos|
      assets.each do |asset|
        zos.put_next_entry(asset.image_file_name)
        zos.print IO.read(asset.image.path)
      end
    end

    file_name = album.title
    if tag
      file_name = file_name + '-' + tag.name
    end
    send_file t.path, :type => "application/zip", :filename => file_name + ".zip"

    t.close
  end

  private
    def album_params
			params.require(:album).permit(:title)
		end

		def require_login
			if current_user == nil
        redirect_to '/login'
      end
    end

    def current_album
      current_user.albums.find(params[:id])
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<a href="<%= album_path(album) %>">
  <div class="album-container col-md-4 col-sm-6">
    <% if album.assets.any? %>
    <div class="album-thumbnail" data-image="<%= album.assets.last.image.url(:medium) %>">
      <% else %>
      <div class="album-thumbnail" data-image="<%= image_path("no_image.png") %>">
        <% end %>
        <div class="album-container-footer col-xs-12">
          <span class="col-xs-6 album-name-container"><%= album.title %></span>
        </div>

      </div>
    </div>
  </a>

app/views/albums/_new.html.erb
<div class="new-album-container col-md-4 col-sm-6">
  <div class="new-album-thumbnail">
    <div class="new-album-container-footer col-xs-12">
      <div class="col-xs-10" id="new-album-form-container">
        <%= form_for @album, :html => { :class => 'create-album-form' } do |f| %>
        <%= f.text_field :title, :placeholder => "New album name", :id => 'album_title' , :required => true, :pattern => ".{1,30}", :title => "1 to 30 characters" %>
      </div>
      <div class="col-xs-2">
        <div id="create-album-button">
          <i class="material-icons prefix flat-red icon-button">done</i>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<div class="row col-xs-12" id="album-assets-container" data-album-id="<%= @album.id %>">

  <div class="well well-sm">
    <span class="lead" id="album-title"><%= best_in_place @album, :title, :place_holder => 'Click me to edit' %></span>
    <div class="pull-right">
      <%= link_to raw('<i class="material-icons prefix flat-midnight-blue icon-button">folder</i>'), distilled_album_path(:album_id => @album.id) %>
      <%= link_to raw('<i class="material-icons prefix flat-green icon-button">style</i>'), distill_album_path(params[:id]) %>

      <%= link_to raw('<i class="material-icons prefix flat-turquoise  icon-button">cloud_download</i>'), download_album_path(:album_id => @album.id, :tag_id => "all") %>
      <span class="delete-album-button">
        <i class="material-icons prefix flat-red icon-button">delete</i>
      </span>

      <%= link_to raw('<i class="material-icons prefix flat-blue icon-button">add_circle</i>'), "", :data => {:toggle => "modal", :target =>".image-uploader-modal"} %>
      <span>
        <%= link_to('delete album', album_path(@album), :class => "no-show delete-album",
              method: :delete ) %>
      </span>
    </div>
  </div>
  <div class="col-xs-12">
    <% if @assets.any? %>
    <div class="clearfix mosaicflow">
      <%= render @assets %>
    </div>
    <% else %>
    <div class="well text-center text-muted">
      You currently have no photos. Click on
      <i class="material-icons prefix flat-blue icon-button-disabled">add_circle</i>
      button to add photos.
    </div>
    <% end %>
  </div>

</div>

<div aria-labelledby="ImageUploaderModal" class="modal fade image-uploader-modal" id="image-uploader-modal" role="dialog" tabindex="-1">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title lead">Photos Uploader</h4>
     </div>
      <div class="modal-body">
      <%= render partial: "assets/new", object: [@album, @asset] %>
      </div>
      <div class="modal-footer">
      <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
    </div>
    </div>
  </div>
</div>

  <%= render partial: 'assets/modal' %>