config/routes.rb
Rails.application.routes.draw do

  #root
  root 'users#index'

  # Users
  match '/signup', :to => 'users#create', :via => [:post], :as => :create_user
  match '/update', :to => 'users#update', :via => [:patch], :as => :update_user
  get '/signup' => 'users#new', as: :signup
  get '/me' => 'users#show', as: :show_user
  get '/update' => 'users#edit', as: :edit_user
  get '/validate_user', :to => "users#validate_user"

  # Sessions
  match '/login', :to => 'sessions#create', :via => [:post], :as => :login_user
  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  # Password Reset
  get '/forgot-password' => 'password_reset#new', as: :forgot_password
  match '/forgot-password', :to => 'password_reset#verify_username', :via => [:post], :as => :verify_username
  get '/forgot-password/1' => 'password_reset#new'
  match '/forgot-password/1', :to => 'password_reset#verify_security_answer', :via => [:post], :as => :verify_security_answer
  get '/forgot-password/reset-password' => 'password_reset#new'
  match '/forgot-password/reset-password', :to => 'password_reset#reset_password', :via => [:patch], :as => :reset_password

  # Albums and assets
  resources :albums do
    resources :assets
    resources :filters do
      resources :tags
    end
  end

  #Filters and tags
  get '/albums/:album_id/distill' => 'filters#show', as: :distill_album
  get '/albums/:album_id/distilled_albums' => 'filters#distilled_albums', as: :distilled_album
  get '/albums/:album_id/distilled_albums/:tag_id' => 'filters#assets_with_tag', as: :distilled_assets
  get '/albums/:album_id/distilled_albums/:tag_id/download' => 'albums#download', as: :download_album

  match '/albums/:album_id/filters/add_filter_to_album', :to => 'filters#add_filter_to_album', :via => [:post], :as => :add_filter_to_album
  match '/albums/:album_id/filters/remove_filter_from_album', :to => 'filters#remove_filter_from_album', :via => [:post], :as => :remove_filter_from_album
  match '/tags/assign_tag_to_asset', :to => 'tags#assign_tag_to_asset', :via => [:post], :as => :assign_tag_to_asset

  get '/albums/:album_id/asset/:asset_id/tags' => "assets#tags", as: :asset_tags
  get '/assets/asset_belongs_to_current_user' => "assets#asset_belongs_to_current_user", as: :asset_belongs_to_current_user


  #Shared Albums
  #resources :shared_albums
  match '/shared_albums/share_album', :to => 'shared_albums#share_album', :via => [:post], :as => :share_album
  get '/shared_album/:shared_album_id' => 'shared_albums#show', as: :shared_album
  match '/shared_albums/delete_album', :to => 'shared_albums#destroy', :via => [:post], :as => :delete_share_album

end

app/models/filter.rb
class Filter < ActiveRecord::Base
  belongs_to :user
  has_many :tags, dependent: :destroy
  has_and_belongs_to_many :albums
  accepts_nested_attributes_for :tags, allow_destroy: :true
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController

  def index
    album = current_user.albums.find(params[:album_id]);
    @filters = album.filters
  end

  def new
    @album = current_user.albums.find(params[:album_id])
    @filter = current_user.filters.new
    @filter.tags.build

  end

  def show
    @album = current_user.albums.find(params[:album_id])
    @filters = current_user.filters
  end

  def create
    @filter = current_user.filters.new(filter_params)
    @album = current_user.albums.find(params[:album_id])
    if @filter.save
      redirect_to distill_album_path(@album)
    else
      render 'new'
    end
  end

  def edit
    @filter = current_user.filters.find(params[:id])
    @album = current_user.albums.find(params[:album_id])
  end

  def update
    @filter = current_user.filters.find(params[:id])
    @album = current_user.albums.find(params[:album_id])

    if @filter.update(filter_params)
      redirect_to distill_album_path(@album)
    else
      render 'edit'
    end
  end

  def distilled_albums
    @album = current_user.albums.find(params[:album_id])
    @filters = []
    @album.assets.each do |a|
      a.tags.each do |t|
        if !@filters.include?(t.filter)
          @filters << t.filter
        end
      end
    end
  end

  def assets_with_tag
    @album = current_user.albums.find(params[:album_id])
    @tag = Tag.find(params[:tag_id])
    @assets = @album.assets.with_tag(@tag)
    @shared_instances =  SharedAlbum.where(album_id: @album.id, tag_id: @tag.id)
  end

  def add_filter_to_album
    filter = current_user.filters.find(params[:filter_id])
    album = current_user.albums.find(params[:album_id])
    if (album && filter)
      unless album.filters.include?(filter)
        album.filters << filter
      end
      render json: { message: "success" }, :status => 200
    else
      render json: { error: 'Sorry, couldn\'t add the filter'}, :status => 400
    end
  end

  def remove_filter_from_album
    filter = current_user.filters.find(params[:filter_id])
    album = current_user.albums.find(params[:album_id])
    if(album && filter)
      album.filters.delete(filter)
      render json: { message: "success" }, :status => 200
    else
      render json: { error: 'Sorry, couldn\'t delete the filter'}, :status => 400
    end
  end

  private
  def find_filter
    @filter = current_user.filters.find(params[:id])
  end

  def filter_params
    params.require(:filter).permit(:name, tags_attributes: [:id, :name, :folderName, :keyboardShortcut, :_destroy])
  end

  def shared_with_users
    shared_instances = SharedAlbum.where(album_id: @album.id, tag_id: @tag.id)
    # users_shared_with = []
    # shared_instances.each do |s|
    #   user = User.find_by_id(s.shared_with)
    #   if user
    #       users_shared_with  << user
    #   end
    # end
    # return users_shared_with
  end
end

app/helpers/filters_helper.rb
module FiltersHelper
  def link_to_add_tags(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n","")})
  end

    def does_filter_belong_to_album(filter_id,album_id)
      if current_user.albums.find(album_id).filters.include?(current_user.filters.find(filter_id))
        concat "checked"
      end
    end

    def tag_names_for_filter(filter)
      tag_names = []
      filter.tags.each do |t|
        tag_names << t.name
      end
      tag_names.join(", ")
    end
end

app/views/filters/_filter.html.erb
<tr>
  <td><%= link_to filter.name, edit_album_filter_path(:id => filter.id) %></td>
  <td><%= tag_names_for_filter(filter) %></td>
  <td>
    <label>
      <input type="checkbox" id="<%= filter.name %>" class="filters-selection-checkboxes" value="<%= filter.id %>" data-album-id="<%= album.id %>" <% does_filter_belong_to_album(filter.id,album.id) %>>
    </label>
  </td>
</tr>

app/views/filters/_form.html.erb
<div class="col-xs-12">
		<%= form_for [@album, @filter], :html => { :class => 'form-horizontal' } do |f| %>
		    <div class="form-group col-xs-8">
		        <%= f.label :name, "Filter Name" , :class => 'col-sm-3 control-label' %>
		        <div class="col-sm-9">
		            <%= f.text_field :name , :class => 'form-control', :required => true, :pattern => ".{1,15}", :title => "1 to 15 characters" %>
		        </div>
		    </div>
	      <div class="col-xs-12">
					<div class="well well-sm ">
						Tags
						<span class="pull-right">
							<%= link_to raw('<i class="material-icons prefix flat-turquoise icon-button">add_circle</i>'), "", :id=>"add_tag" %>
						</span>
					</div>
	          <%= f.fields_for :tags do |tag| %>
	          	<%= render 'tag_fields', f: tag %>
	          <% end %>
						<%= link_to_add_tags "Add Tag", f, :tags %>
	      </div>

		    <div class="form-group">
		        <div class="col-xs-2 col-xs-offset-10">
		            <%= submit_tag "Save" , :class => 'btn btn-primary' %>
		        </div>
		    </div>
		<% end %>
</div>

app/views/filters/_tag_fields.html.erb
<div class="fieldset">
    <div class="panel panel-default col-xs-12 col-sm-8 col-md-5">
        <div class="panel-body">
              <div class="form-group">
                <%= f.label :name , raw(icon("bookmark")), :class => 'col-xs-2 control-label' %>
                  <div class="col-xs-10">
                      <%= f.text_field :name , :class => 'form-control tag_name_field', :placeholder => "Tag Name", :required => true %>
                  </div>
              </div>
              <div class="form-group">
                  <%= f.label :name , raw(icon("keyboard")), :class => 'col-xs-2 control-label' %>
                  <div class="col-xs-10">
                      <%= f.text_field :keyboardShortcut , :class => 'form-control keyboard_shortcut_field', :placeholder => "Keyboard Shortcut", :required => true %>
                  </div>
              </div>
              <%= f.hidden_field :_destroy %>
              <%= link_to raw('<i class="material-icons prefix success-contrast icon-button">delete</i>'),"#", class: "remove_fields pull-right" %>
        </div>
     </div>
     <div class="col-xs-1"></div>
</div>

app/views/filters/assets_with_tag.html.erb
<div class="well well-sm">
  <span class="lead"><%= link_to @album.title, @album %> > <%= link_to "Distilled Albums", distilled_album_path %> > <%= @tag.name %></span>
  <div class="pull-right">
    <%= link_to raw('<i class="material-icons prefix flat-blue icon-button">folder_shared</i>'), "", :data => {:toggle => "modal", :target =>".album-share-modal"} %>
    <%= link_to raw('<i class="material-icons prefix flat-midnight-blue icon-button">cloud_download</i>'), download_album_path %>
  </div>
</div>
<div class="col-xs-12">
  <% if @assets.any? %>
  <div class="clearfix mosaicflow">
    <%= render @assets %>
  </div>
  <% else %>
  <div class="well text-center text-muted">
    You currently have no photos with the tag - <span class="text-primary"> <b><%= @tag.name %></b></span>
  </div>
  <% end %>
</div>
<%= render partial: 'assets/modal' %>
<%= render partial: 'shared_albums/new' %>

app/views/filters/distilled_albums.html.erb
<div class="well well-sm">
  <span class="lead"><%= link_to @album.title, @album %> > Distilled Albums</span>
</div>
<% @filters.each do |f| %>
<div class="row col-xs-12">
        <div class="row col-xs-12">
            <p class="silver-bg">  <span class="lead distilled-album-name"><%= f.name %></span></p>
       </div>
      <% f.tags.each do |t| %>
         <% if @album.assets.with_tag(t).any? %>
               <div class="col-xs-3">
                 <a href="<%= distilled_assets_path(:tag_id => t.id) %>" class="thumbnail">
                   <%=	image_tag(@album.assets.with_tag(t).last.image.url(:small)) %>
                 </a>
                 <div class="caption">
                   <h5 class="text-center"><%= t.name %> (<%= @album.assets.with_tag(t).count %>)</h5>
                 </div>
               </div>
         <% end %>
      <% end %>
</div>
<% end %>

app/views/filters/edit.html.erb
<div class="row col-xs-12">
  <div class="well well-sm">
    <span class="lead"><%= link_to @album.title, @album %> > <%= link_to "Filters", distill_album_path(@album) %></span>
  </div>
  <% if @filter.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
       <strong>Oops!</strong>
       <% @filter.errors.each do |field, msg| %>
          <li><%= msg %></li>
       <% end %>
    </div>
  <% end %>
</div>
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="panel-title">Update Filter</span>
      </div>

      <div class="panel-body">
          <%= render partial: "form", object: @filter %>
      </div>
  </div>

</div>

app/views/filters/new.html.erb
<div class="row col-xs-12">
  <div class="well well-sm">
    <span class="lead"><%= link_to @album.title, @album %> > <%= link_to "Filters", distill_album_path(@album) %></span>
  </div>
  <% if @filter.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
       <strong>Oops!</strong>
       <% @filter.errors.each do |field, msg| %>
          <li><%= msg %></li>
       <% end %>
    </div>
  <% end %>
</div>
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="panel-title">Create Filter</span>
      </div>

      <div class="panel-body">
          <%= render partial: "form", object: @filter %>
      </div>
  </div>

</div>

app/views/filters/show.html.erb
<div class="row col-xs-12">
  <div class="well well-sm">
    <span class="lead"><%= link_to @album.title, @album %> > Filters</span>
  </div>
  <div class="row col-xs-12 col-md-6 col-md-offset-3">
    <div class="panel panel-success">
      <div class="panel-heading" id="available-filters-panel">
        <span class="panel-title">Available Filters</span>
        <span class="pull-right">
          <%= link_to raw('<i class="material-icons prefix success-contrast icon-button">add_circle</i>'), new_album_filter_path %>
        </span>
      </div>
      <div class="panel-body">
          <table class="table">
            <thead>
              <tr>
                <th>Filter</th>
                <th>Tags</th>
                <th>Select</th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: 'filter', collection: @filters, locals: {album: @album} %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>